apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.9.2
          imagePullPolicy: IfNotPresent
          command:
            - logstash
            - -f
            - /etc/logstash/conf.d/logstash.conf
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: config-volume
              mountPath: /etc/logstash/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
