apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchserviceapi
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchserviceapi
  template:
    metadata:
      labels:
        app: searchserviceapi
    spec:
      containers:
        - name: searchserviceapi
          image: tanlp/searchserviceapi
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "400m"
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Postgres
              value: "Host=elearningdb;Database=SearchServiceDb;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: searchserviceapi
spec:
  type: NodePort
  selector:
    app: searchserviceapi
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
