apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlistapi
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlistapi
  template:
    metadata:
      labels:
        app: wishlistapi
    spec:
      containers:
        - name: wishlistapi
          image: tanlp/wishlistapi
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "400m"
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Postgres
              value: "Host=elearningdb;Database=LearningServiceDb;Username=postgres;Password=postgres"
            - name: GrpcSettings__CourseUri
              value: "http://coursemanagerapi:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: wishlistapi
spec:
  selector:
    app: wishlistapi
  ports:
    - port: 8080
      targetPort: 8080
