apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursemanagerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coursemanagerapi
  template:
    metadata:
      labels:
        app: coursemanagerapi
    spec:
      containers:
        - name: coursemanagerapi
          image: tanlp/coursemanagerapi
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8082
              name: grpc
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Postgres
              value: "Host=elearningdb;Database=CourseManagerDb;Username=postgres;Password=postgres"
            - name: GrpcSettings__LearningServiceUri
              value: "http://learningserviceapi:8082"
            - name: GrpcSettings__VideoManagerUri
              value: "http://videomanagerapi:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: coursemanagerapi
spec:
  selector:
    app: coursemanagerapi
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 8082
      targetPort: 8082
