apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderingapi
  template:
    metadata:
      labels:
        app: orderingapi
    spec:
      containers:
        - name: orderingapi
          image: tanlp/orderingapi
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Postgres
              value: "Host=elearningdb;Database=OrderingDb;Username=postgres;Password=postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: orderingapi
spec:
  selector:
    app: orderingapi
  ports:
    - port: 8080
      targetPort: 8080
